package tools

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// DocGenTool creates documents (HTML, CSV, Markdown) from natural language descriptions.
// Generates HTML for rich documents, CSV for spreadsheets, and Markdown for docs.
type DocGenTool struct {
	workspace string
}

func NewDocGenTool(workspace string) *DocGenTool {
	return &DocGenTool{workspace: workspace}
}

func (t *DocGenTool) Name() string { return "create_document" }

func (t *DocGenTool) Description() string {
	return "Create a document file from content. Supports formats: " +
		"html (rich document with styling, can be opened as PDF via browser print), " +
		"csv (spreadsheet data, opens in Excel/Sheets), " +
		"md (Markdown documentation). " +
		"Use this to generate reports, spreadsheets, invoices, summaries, or any structured document."
}

func (t *DocGenTool) Parameters() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"filename": map[string]any{
				"type":        "string",
				"description": "Output filename (e.g. 'report.html', 'data.csv', 'notes.md')",
			},
			"format": map[string]any{
				"type":        "string",
				"enum":        []string{"html", "csv", "md"},
				"description": "Document format: html (rich document), csv (spreadsheet), md (markdown)",
			},
			"title": map[string]any{
				"type":        "string",
				"description": "Document title (used in HTML head and header)",
			},
			"content": map[string]any{
				"type":        "string",
				"description": "The document body content. For HTML: valid HTML content. For CSV: comma-separated rows. For MD: markdown text.",
			},
		},
		"required": []string{"format", "content"},
	}
}

func (t *DocGenTool) Execute(ctx context.Context, args map[string]any) *ToolResult {
	format, _ := args["format"].(string)
	content, _ := args["content"].(string)
	title, _ := args["title"].(string)
	filename, _ := args["filename"].(string)

	if content == "" {
		return ErrorResult("create_document: content is required")
	}

	if title == "" {
		title = "Document"
	}

	// Auto-generate filename if not provided
	if filename == "" {
		ts := time.Now().Format("20060102-150405")
		switch format {
		case "csv":
			filename = fmt.Sprintf("document-%s.csv", ts)
		case "md":
			filename = fmt.Sprintf("document-%s.md", ts)
		default:
			filename = fmt.Sprintf("document-%s.html", ts)
			format = "html"
		}
	}

	// Ensure correct extension
	if format == "html" && !strings.HasSuffix(filename, ".html") && !strings.HasSuffix(filename, ".htm") {
		filename += ".html"
	} else if format == "csv" && !strings.HasSuffix(filename, ".csv") {
		filename += ".csv"
	} else if format == "md" && !strings.HasSuffix(filename, ".md") {
		filename += ".md"
	}

	outPath := filepath.Join(t.workspace, filename)
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return ErrorResult("create_document: failed to create directory: " + err.Error())
	}

	var output string
	switch format {
	case "html":
		output = wrapHTML(title, content)
	case "csv":
		output = content
	case "md":
		output = content
	default:
		return ErrorResult("create_document: unsupported format: " + format)
	}

	if err := os.WriteFile(outPath, []byte(output), 0o644); err != nil {
		return ErrorResult("create_document: failed to write file: " + err.Error())
	}

	info, _ := os.Stat(outPath)
	size := int64(0)
	if info != nil {
		size = info.Size()
	}

	result := fmt.Sprintf("Document created: %s (%d bytes, %s format)\nPath: %s", filename, size, format, outPath)
	return &ToolResult{ForLLM: result, ForUser: result, IsError: false}
}

func wrapHTML(title, body string) string {
	return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>` + title + `</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #333; line-height: 1.6; }
  h1 { color: #1a1a2e; border-bottom: 2px solid #e0e0e0; padding-bottom: 10px; }
  h2 { color: #2a2a4e; margin-top: 30px; }
  table { border-collapse: collapse; width: 100%; margin: 20px 0; }
  th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
  th { background: #f5f5f5; font-weight: 600; }
  tr:nth-child(even) { background: #fafafa; }
  code { background: #f0f0f0; padding: 2px 6px; border-radius: 3px; font-size: 0.9em; }
  pre { background: #f5f5f5; padding: 15px; border-radius: 5px; overflow-x: auto; }
  .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; color: #999; font-size: 0.85em; }
  @media print { body { margin: 0; } }
</style>
</head>
<body>
<h1>` + title + `</h1>
` + body + `
<div class="footer">Generated by Sofia</div>
</body>
</html>`
}
