package config

// GitHubAutonomyConfig controls the cron-driven poller that watches
// external repositories for issues labeled `Label` and kicks off the
// fix-github-issue workflow for each new one.
//
// This block only affects the autonomous pipeline; the interactive
// `gh`/`git` tools (for on-demand agent usage) are configured separately
// under Tools.GitHub.
type GitHubAutonomyConfig struct {
	Enabled bool `json:"enabled"              env:"SOFIA_GITHUB_AUTONOMY_ENABLED"`

	// Repos lists "owner/repo" names to watch. Empty list disables the
	// poller even when Enabled is true — prevents accidental "watch
	// everything" behavior.
	Repos []string `json:"repos,omitempty"      env:"SOFIA_GITHUB_AUTONOMY_REPOS" envSeparator:","`

	// Label is the opt-in issue label that makes an issue eligible.
	// Default: "sofia-autofix".
	Label string `json:"label,omitempty"      env:"SOFIA_GITHUB_AUTONOMY_LABEL"`

	// PollMinutes is the cron interval. Minimum 1, default 10.
	PollMinutes int `json:"poll_minutes,omitempty" env:"SOFIA_GITHUB_AUTONOMY_POLL_MINUTES"`

	// MaxConcurrent caps how many fix workflows may run in parallel per
	// poll batch. 0 defaults to 2 — enough for meaningful throughput
	// without turning the laptop into a space heater.
	MaxConcurrent int `json:"max_concurrent,omitempty" env:"SOFIA_GITHUB_AUTONOMY_MAX_CONCURRENT"`

	// WorkspaceRoot is the base directory for per-issue repo checkouts.
	// When empty the adapter falls back to a Sofia-managed path under
	// the workspace dir.
	WorkspaceRoot string `json:"workspace_root,omitempty" env:"SOFIA_GITHUB_AUTONOMY_WORKSPACE_ROOT"`

	// BranchPrefix prefixes the autogenerated branch name. Default
	// "sofia-autofix/". Resulting branch: "sofia-autofix/<issue-number>".
	BranchPrefix string `json:"branch_prefix,omitempty" env:"SOFIA_GITHUB_AUTONOMY_BRANCH_PREFIX"`

	// UseFork controls whether we first run `gh repo fork --remote` to
	// push to a fork (default when user lacks write access). When false
	// we push directly to origin.
	UseFork bool `json:"use_fork" env:"SOFIA_GITHUB_AUTONOMY_USE_FORK"`
}

// DefaultGitHubAutonomy returns a safe set of defaults. Callers apply this
// AFTER unmarshaling user config so blank fields get sensible values.
func DefaultGitHubAutonomy(cfg GitHubAutonomyConfig) GitHubAutonomyConfig {
	if cfg.Label == "" {
		cfg.Label = "sofia-autofix"
	}
	if cfg.PollMinutes <= 0 {
		cfg.PollMinutes = 10
	}
	if cfg.MaxConcurrent <= 0 {
		cfg.MaxConcurrent = 2
	}
	if cfg.BranchPrefix == "" {
		cfg.BranchPrefix = "sofia-autofix/"
	}
	return cfg
}
