apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "[logstash-]YYYY.MM.DD"
    jsonData:
      timeField: "@timestamp"
      interval: Daily
      logLevelField: "level"
      logMessageField: "message"
      maxConcurrentShardRequests: 5
      timeInterval: "1m"
    editable: true